appName: service-1
namespace: service-1

port: 8081

replicas: 2

image:
  repository: ""
  tag: v1.0
  pullPolicy: IfNotPresent

limits:
  memory: "512Mi"
  cpu: "500m"

requests:
  memory: "256Mi"
  cpu: "250m"

PUBSUB_NAME: rbt-pubsub
TOPIC_NAME: kf-one
DAPR_SECRET_STORE: localsecretstore
CONFIG_STORE_NAME: pg-configstore