apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: az-configstore
  namespace: {{ .Values.namespace }}
spec:
  type: configuration.azure.appconfig
  version: v1
  metadata:
  - name: connectionString # connectionString should not be used when Azure Authentication mechanism is used.
    value: {{ .Values.appConfigConnectionString }}
  - name: subscribePollInterval # Optional
    value: {{ .Values.subscribePollInterval }}
