apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: {{ .Values.namespace }}
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: {{ .Values.zipkinEndpoint }}
