apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pg-configstore
  namespace: {{ .Values.namespace }}
spec:
  type: configuration.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host={{ .Values.pgHost }} user={{ .Values.pgUser }} password={{ .Values.pgPwd }} port={{ .Values.pgPort }} connect_timeout=10 database={{ .Values.pgDbName }}"
    - name: table
      value: {{ .Values.configTable }}