apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-configstore
  namespace: {{ .Values.namespace }}
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
auth:
  secretStore: kubernetes