apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.redisHost }}
  - name: redisPassword
    value: {{ .Values.redisPassword }}
