apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: service1-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: {{ .Values.zipkinEndpoint }}
