apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.appName }}-config
    labels:
        app: {{ .Values.appName }}
data:
    # Add your key-value pairs here
    PUBSUB_NAME: {{ .Values.PUBSUB_NAME }}
    TOPIC_NAME: {{ .Values.TOPIC_NAME }}
    DAPR_SECRET_STORE: {{ .Values.DAPR_SECRET_STORE }}
    CONFIG_STORE_NAME: {{ .Values.CONFIG_STORE_NAME }}
    DAPR_HOST: {{ .Values.DAPR_HOST }}